name: CI - Build

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ secrets.ACR_REGISTRY }}
  ASPNET_IMAGE_NAME: aiportfolioanalysis
  CADDY_IMAGE_NAME: caddy-proxy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read          # Required for accessing workflow run metadata

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Extract ASP.NET metadata
      id: aspnet-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.ASPNET_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,format=short,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract Caddy metadata
      id: caddy-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.CADDY_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,format=short,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push ASP.NET Docker image
      uses: docker/build-push-action@v5
      id: aspnet-build
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.aspnet-meta.outputs.tags }}
        labels: ${{ steps.aspnet-meta.outputs.labels }}

    - name: Generate Caddyfile for environment
      run: |
        # Determine environment based on branch
        if [ "${{ github.ref_name }}" = "main" ]; then
          CADDY_DOMAIN="aiportfolioanalysis-prod.southcentralus.azurecontainer.io"
          echo "Building for production environment"
        else
          CADDY_DOMAIN="aiportfolioanalysis-test.southcentralus.azurecontainer.io"
          echo "Building for test environment"
        fi
        
        # Generate Caddyfile from template
        sed -e "s/__CADDY_DOMAIN__/$CADDY_DOMAIN/g" \
            -e "s/__LETS_ENCRYPT_EMAIL__/{env.LETS_ENCRYPT_EMAIL}/g" \
            Caddyfile.template > Caddyfile
        
        echo "Generated Caddyfile for domain: $CADDY_DOMAIN"
        echo "Caddyfile contents:"
        cat Caddyfile

    - name: Build and push Caddy Docker image
      uses: docker/build-push-action@v5
      id: caddy-build
      with:
        context: .
        file: ./Dockerfile.caddy
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.caddy-meta.outputs.tags }}
        labels: ${{ steps.caddy-meta.outputs.labels }}

