name: CI - Build

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ secrets.ACR_REGISTRY }}
  ASPNET_IMAGE_NAME: aiportfolioanalysis
  CADDY_IMAGE_NAME: caddy-proxy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read          # Required for accessing workflow run metadata

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Extract ASP.NET metadata
      id: aspnet-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.ASPNET_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,format=short,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract Caddy metadata
      id: caddy-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.CADDY_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,format=short,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push ASP.NET Docker image
      uses: docker/build-push-action@v5
      id: aspnet-build
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.aspnet-meta.outputs.tags }}
        labels: ${{ steps.aspnet-meta.outputs.labels }}

    - name: Build and push Caddy Docker image
      uses: docker/build-push-action@v5
      id: caddy-build
      with:
        context: .
        file: ./Dockerfile.caddy
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.caddy-meta.outputs.tags }}
        labels: ${{ steps.caddy-meta.outputs.labels }}

